QE: quadratic-equation_functions_header.h quadratic-equation_functions.cpp quadratic-equation_main.cpp quadratic-equation_tests_header.h quadratic-equation_tests.cpp
	g++ -o $@ $^

%.o:%.c
	g++ -c -o $@ $<
